# this deploys to VM-Env
# http://13.66.39.43/ - demoignt02 - VM01
# http://40.84.235.28/ - demoignt12 - VM02
# http://52.171.218.16/ - demoignt03 - VM03


trigger: none
pr: none

resources:
 pipelines:
 - pipeline: build
   source: raimdtu.AspDotNetCore
   trigger: 
    branches:
    - master

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: VMDeploy
    displayName: web
    pool: default
    environment:
      name: VM-Env
      resourceType: VirtualMachine
    strategy:
      rolling:
        maxBatchSize: 1
        preDeploy:
          steps:
            - download: build
              artifact: drop
            - script: echo Hello, world! This is pre-deploy
              displayName: 'Run a one-line script'

        deploy:
          steps:
            - download: build
              artifact: drop
            - script: echo Hello, world! This is deploy
              displayName: 'Run a one-line script'

        routeTraffic:
          steps:
            - download: build
              artifact: drop
            - script: echo Hello, world! This is routeTraffic
              displayName: 'Run a one-line script'

        postRouteTraffic:
          steps:
            - download: build
              artifact: drop
            - script: echo Hello, world! This is postRouteTraffic
              displayName: 'Run a one-line script'

        on:
          failure:
            steps:
            - download: build
              artifact: drop
            - script: echo Hello, world! This is on failure
              displayName: 'Run a one-line script'

          success:
            steps:
            - download: build
              artifact: drop
            - script: echo Hello, world! This is on success
              displayName: 'Run a one-line script' 

